#!/usr/bin/env python

sources = """
krad_sdl_opengl_display.c
../krad_gui/krad_gui.c 
""".split()

includedirs = """
../krad_gui/
""".split()

libs = ["sdl", "gtk+-3.0", "gl", "glu", "libswscale", "libavutil"]

def configure(conf):
	
	for l in libs:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')


def build(bld):

	bld(features = 'c cprogram', 
		source = sources + ["krad_sdl_opengl_display_gui_test.c"], 
		includes = includedirs, 
		target = "krad_sdl_opengl_display_gui_test", 
		uselib = libs)

	bld(features = 'c cprogram', 
		source = sources + ["krad_vsync_test.c"], 
		includes = includedirs, 
		target = "krad_vsync_test", 
		uselib = libs)
