#!/usr/bin/env python

programs = """
krad_sdl_opengl_display_gui_test.c
krad_sdl_opengl_display_test.c
krad_sdl_overlay_display_test.c
krad_vsync_test.c
krad_jitter_test.c
""".split()

sources = """
krad_sdl_opengl_display.c
krad_sdl_overlay_display.c
""".split()

depsources = """
../krad_gui/krad_gui.c 
""".split()

includedirs = """
../krad_gui/
""".split()

libs = ["sdl", "gtk+-3.0", "gl", "glu", "libswscale", "libavutil"]

def configure(conf):
	
	for l in libs:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')


def build(bld):


	for p in programs:

		bld(features = 'c cprogram', 
			source = sources + depsources + [p], 
			includes = includedirs, 
			target = p.replace(".c", ""), 
			uselib = libs + ["m"])

