#!/usr/bin/env python

programs1 = """
krad_dirac_test.c
""".split()

sources = """
krad_dirac.c
""".split()

depsources1 = """
""".split()

includedirs1 = """
""".split()


libs1 = ["orc-0.4", "schroedinger-1.0"]

def configure(conf):
	
	for l in libs1:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')



def build(bld):


	for p in programs1:

		bld(features = 'c cprogram', 
			source = sources + depsources1 + [p], 
			includes = includedirs1, 
			target = p.replace(".c", ""), 
			uselib = libs1)


