#! /usr/bin/env python

sources = """
krad_gui_gtk_test.c 
krad_gui.c 
krad_gui_gtk.c
""".split()

conf.check_cfg(package='gtk+-3.0', uselib_store='GTK', args='--cflags --libs')
conf.env.append_unique('CFLAGS', ['-g'])

bld(features = 'c cprogram', source = sources, target = "krad_gui_gtk_test", uselib = "GTK")
