#!/usr/bin/env python

sources = """
krad_gui.c 
krad_gui_gtk.c
""".split()

includedirs = """
.
""".split()

libs = ["gtk+-3.0"]

def configure(conf):
	
	for l in libs:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')
	
def build(bld):

	bld(features = 'c cprogram', 
		source = sources + ["krad_gui_gtk_test.c"], 
		includes = includedirs, 
		target = "krad_gui_gtk_test", 
		uselib = libs)

