#!/usr/bin/env python

import os

programs = """
krad_radio.c
krad_radio_ap.c
krad_radio_vp.c
""".split()

libsources = """
../lib/krad_system/krad_system.c
../lib/krad_ebml/krad_ebml.c
../lib/krad_ring/krad_ring.c
../lib/krad_transmitter/krad_transmitter.c
../lib/krad_link/krad_link_common.c
../lib/krad_ipc/krad_ipc_client.c
../lib/krad_osc/krad_osc.c
../lib/krad_tone/krad_tone.c
../lib/krad_compositor/krad_compositor_common.c
""".split()

includedirs = """
../lib/krad_x264/
../lib/krad_compositor/
../lib/krad_ticker/
../lib/krad_xmms2/
../lib/krad_y4m/
../lib/krad_framepool/
../lib/krad_web/
../lib/krad_web/ext/
../lib/krad_web/ext/libwebsockets/
../lib/krad_web/res/
../lib/krad_vhs/
../lib/krad_sfx/
../lib/krad_tone/
../lib/krad_ipc/
../lib/krad_tags/
../lib/krad_audio/
../lib/krad_theora/
../lib/krad_jack/
../lib/krad_alsa/
../lib/krad_mixer/
../lib/krad_osc/
../lib/krad_xmms2/
../lib/krad_wayland/
../lib/krad_vpx/
../lib/krad_v4l2/
../lib/krad_flac/
../lib/krad_vorbis/
../lib/krad_gui/
../lib/krad_opus/
../lib/krad_radio/
../lib/krad_ring/
../lib/krad_ogg/
../lib/krad_io/
../lib/krad_link/
../lib/krad_transmitter/
../lib/krad_container/
../lib/krad_x11/
../lib/krad_udp/
../lib/krad_codec2/
../lib/krad_system/
../lib/krad_decklink/
../lib/krad_ebml/
../lib/krad_legacy/
/usr/local/include
/usr/include
""".split()

shlibs = ["cairo", "pangocairo", "opus", "xmms2-client", "vpx"]

stlibs = []
syslibs = ['m', 'dl', 'z']
syslibs2 = ['rt']

def check_system(systm):

	global programs
	global includedirs
	global libsources
	global shlibs
	global syslibs
	global syslibs2

	if systm.env['IS_LINUX']:
		shlibs = shlibs + ["alsa"]    
		libsources = ["../lib/krad_alsa/krad_alsa.c", "../lib/krad_alsa/krad_alsa_seq.c"] + libsources
		programs = ["krad_radio_ev.c"] + programs
		syslibs = syslibs + syslibs2


	if systm.env['IS_MACOSX']:
		libsources = ["../lib/krad_legacy/krad_mach.c"] + libsources
		includedirs = ["/opt/libjpeg-turbo/include"] + includedirs
		shlibs = shlibs + ['turbojpeg']

def configure(conf):

	global programs
	global shlibs
	global syslibs
	check_system(conf)

	for l in syslibs:
		conf.check(lib = l, cflags='-Wall', uselib_store = l)

	for l in shlibs:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')

	for l in stlibs:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs --static')

def build(bld):

	global programs
	global shlibs
	global syslibs
	global syslibs2
	check_system(bld)

	bld.shlib(
		source = libsources, 
		includes = includedirs, 
		target = "kradradio_client",
		uselib = shlibs + stlibs + syslibs)

	for p in programs:

		bld(features = 'c cprogram', 
			source = [p], 
			includes = includedirs, 
			target = p.replace(".c", ""),
			use = ["kradradio_client"],
			uselib = shlibs + stlibs + syslibs)

