#!/usr/bin/env python

programs = """
krad_ebml_player_cmd.c
krad_ebml_player_gui_gtk.c
""".split()

sources = """
krad_ebml_player.c
""".split()

depsources = """
../krad_tone/krad_tone.c
../krad_audio/krad_audio.c
../krad_jack/krad_jack.c
../krad_pulse/krad_pulse.c
../krad_alsa/krad_alsa.c
../krad_vpx/krad_vpx.c
../krad_vorbis/krad_vorbis.c
../krad_opus/krad_opus.c
../krad_opus/opus_header.c
../krad_gui/krad_gui.c
../krad_gui/krad_gui_gtk.c
../krad_display/krad_sdl_opengl_display.c
""".split()

includedirs = """
../krad_tone/
../krad_audio/
../krad_jack/
../krad_pulse/
../krad_alsa/
../krad_vpx/
../krad_vorbis/
../krad_display/
../krad_gui/
../krad_opus/
../../krad_ebml/
""".split()

libs = ["vorbis", "speex", "speexdsp", "opus", "sdl", "gtk+-3.0", "gl", "glu", "flac", "libpulse", "jack", "alsa", "vpx", "libswscale", "libavutil"]

def configure(conf):
	
	for l in libs:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')


def build(bld):


	for p in programs:

		bld(features = 'c cprogram', 
			source = sources + depsources + [p], 
			includes = includedirs, 
			target = p.replace(".c", ""),
			use = "kradebml",
			uselib = libs)
