#!/usr/bin/env python

#krad_ebml_test.c
#krad_ebml_write_test.c

programs = """
krad_radio.c
""".split()

programs2 = """
krad_radio_gtk.c
krad_radio_cmd.c
krad_ebml_fileinfo.c
""".split()

programs3 = """
krad_xpdr.c
""".split()

sources = """
""".split()

depsources = """
../krad_tools/krad_link/krad_link_common.c
../krad_tools/krad_system/krad_system.c
../krad_tools/krad_compositor/krad_compositor.c
../krad_tools/krad_framepool/krad_framepool.c
../krad_tools/krad_web/ext/cJSON.c
../krad_tools/krad_web/krad_http.c
../krad_tools/krad_web/krad_websocket.c
../krad_tools/krad_effects/digilogue.c
../krad_tools/krad_effects/fastlimiter.c
../krad_tools/krad_effects/util/blo.c
../krad_tools/krad_effects/util/db.c
../krad_tools/krad_effects/util/buffer.c
../krad_tools/krad_effects/util/iir.c
../krad_tools/krad_effects/util/rms.c
../krad_tools/krad_effects/pass.c
../krad_tools/krad_effects/djeq.c
../krad_tools/krad_effects/hardlimiter.c
../krad_tools/krad_effects/sidechain_comp.c
../krad_tools/krad_ipc/krad_ipc_client.c
../krad_tools/krad_ipc/krad_ipc_server.c
../krad_tools/krad_tags/krad_tags.c
../krad_tools/krad_radio/krad_radio.c
../krad_tools/krad_mixer/krad_mixer.c
../krad_tools/krad_tone/krad_tone.c
../krad_tools/krad_audio/krad_audio.c
../krad_tools/krad_jack/krad_jack.c
../krad_tools/krad_pulse/krad_pulse.c
../krad_tools/krad_alsa/krad_alsa.c
../krad_tools/krad_vpx/krad_vpx.c
../krad_tools/krad_dirac/krad_dirac.c
../krad_tools/krad_theora/krad_theora.c
../krad_tools/krad_vorbis/krad_vorbis.c
../krad_tools/krad_flac/krad_flac.c
../krad_tools/krad_opus/krad_opus.c
../krad_tools/krad_opus/opus_header.c
../krad_tools/krad_gui/krad_gui.c
../krad_tools/krad_v4l2/krad_v4l2.c
../krad_tools/krad_gui/krad_gui_gtk.c
../krad_tools/krad_ring/krad_ring.c
../krad_tools/krad_link/krad_link.c
../krad_tools/krad_xpdr/krad_xpdr.c
../krad_tools/krad_io/krad_io.c
../krad_tools/krad_ogg/krad_ogg.c
../krad_tools/krad_container/krad_container.c
../krad_tools/krad_x11/krad_x11.c
../krad_tools/krad_udp/krad_udp.c
../krad_tools/krad_codec2/krad_codec2.c
../krad_tools/krad_decklink/krad_decklink.c
../krad_tools/krad_decklink/krad_decklink_capture.cpp
../krad_tools/krad_decklink/vendor/DeckLinkAPIDispatch.cpp
""".split()

depsources2 = """
../krad_tools/krad_system/krad_system.c
../krad_tools/krad_link/krad_link_common.c
../krad_tools/krad_ipc/krad_ipc_client.c
""".split()

includedirs = """
../krad_tools/krad_compositor/
../krad_tools/krad_framepool/
../krad_tools/krad_web/
../krad_tools/krad_web/ext/
../krad_tools/krad_web/res/
../krad_tools/krad_effects/
../krad_tools/krad_tone/
../krad_tools/krad_ipc/
../krad_tools/krad_tags/
../krad_tools/krad_audio/
../krad_tools/krad_dirac/
../krad_tools/krad_theora/
../krad_tools/krad_jack/
../krad_tools/krad_pulse/
../krad_tools/krad_alsa/
../krad_tools/krad_mixer/
../krad_tools/krad_vpx/
../krad_tools/krad_v4l2/
../krad_tools/krad_flac/
../krad_tools/krad_vorbis/
../krad_tools/krad_gui/
../krad_tools/krad_opus/
../krad_tools/krad_radio/
../krad_tools/krad_ring/
../krad_tools/krad_ogg/
../krad_tools/krad_io/
../krad_tools/krad_link/
../krad_tools/krad_xpdr/
../krad_tools/krad_container/
../krad_tools/krad_x11/
../krad_tools/krad_udp/
../krad_tools/krad_codec2/
../krad_tools/krad_system/
../krad_tools/krad_decklink/
../krad_tools/krad_decklink/vendor
../krad_ebml/
/usr/local/include
/usr/include
""".split()

libs = ["samplerate", "codec2", "turbojpeg", "theora", "theoraenc", "theoradec", "vorbis", "vorbisenc", "opus", "x11-xcb", "xcb-atom", "xcb-image", "xcb", "x11", "orc-0.4", "schroedinger-1.0", "gtk+-3.0", "gl", "glu", "flac", "libpulse", "jack", "alsa", "vpx", "libswscale", "libavutil", "websockets"]

def configure(conf):
	
	for l in libs:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')


def build(bld):

	cmd = 'xxd -i krad_tools/krad_web/res/krad_radio.html krad_tools/krad_web/res/krad_radio.html.h'
	bld.exec_command(cmd)

	cmd = 'xxd -i krad_tools/krad_web/res/krad_radio.js krad_tools/krad_web/res/krad_radio.js.h'
	bld.exec_command(cmd)

	for p in programs:

		bld(features = 'c cprogram cxx cxxprogram', 
			source = sources + depsources + [p], 
			includes = includedirs, 
			target = p.replace(".c", ""),
			use = ["kradebml", "m"],
			uselib = libs)

	for p in programs2:

		bld(features = 'c cprogram', 
			source = sources + depsources2 + [p], 
			includes = includedirs, 
			target = p.replace(".c", ""),
			use = ["kradebml", "m"],
			uselib = libs)

