#!/usr/bin/env python

programs = """
krad_v4l2_test.c
""".split()

sources = """
krad_v4l2.c
""".split()

depsources = """
""".split()

includedirs = """
""".split()

libs = ['turbojpeg']

def configure(conf):
	
	conf.check(header_name='linux/videodev2.h', features='c cprogram')
	
	for l in libs:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')


def build(bld):


	for p in programs:

		bld(features = 'c cprogram', 
			source = sources + depsources + [p], 
			includes = includedirs, 
			target = p.replace(".c", ""), 
			uselib = libs)

