#!/usr/bin/env python

programs = """
krad_ebml_cluster_test.c
krad_ebml_video_sdl_overlay_test.c
krad_v4l2_vpx_display_test.c
krad_ebml_file_broadcast.c
krad_ebml_video_sdl_opengl_hud_test.c
krad_mousetest.c
krad_v4l2_vpx_ebml_test.c
krad_ebml_video_sdl_opengl_test.c
krad_sdl_opengl_display_signal_generator.c
krad_v4l2_vpx_test.c
krad_cam.c
""".split()

sources = """
""".split()

depsources = """
../krad_tone/krad_tone.c
../krad_audio/krad_audio.c
../krad_jack/krad_jack.c
../krad_pulse/krad_pulse.c
../krad_alsa/krad_alsa.c
../krad_vpx/krad_vpx.c
../krad_dirac/krad_dirac.c
../krad_theora/krad_theora.c
../krad_vorbis/krad_vorbis.c
../krad_flac/krad_flac.c
../krad_opus/krad_opus.c
../krad_opus/opus_header.c
../krad_gui/krad_gui.c
../krad_v4l2/krad_v4l2.c
../krad_gui/krad_gui_gtk.c
../krad_display/krad_sdl_opengl_display.c
../krad_display/krad_sdl_overlay_display.c
""".split()

includedirs = """
../krad_tone/
../krad_audio/
../krad_dirac/
../krad_theora/
../krad_jack/
../krad_pulse/
../krad_alsa/
../krad_vpx/
../krad_v4l2/
../krad_flac/
../krad_vorbis/
../krad_display/
../krad_gui/
../krad_opus/
../../krad_ebml/
""".split()

libs = ["turbojpeg", "theora", "theoraenc", "theoradec", "vorbis", "speex", "speexdsp", "opus", "sdl", "orc-0.4", "schroedinger-1.0", "gtk+-3.0", "gl", "glu", "flac", "libpulse", "jack", "alsa", "vpx", "libswscale", "libavutil"]

def configure(conf):
	
	for l in libs:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')


def build(bld):


	for p in programs:

		bld(features = 'c cprogram', 
			source = sources + depsources + [p], 
			includes = includedirs, 
			target = p.replace(".c", ""),
			use = "kradebml",
			uselib = libs)
