#ifndef KRAD_EASING_COMMON_H
#define KRAD_EASING_COMMON_H

typedef enum {
	LINEAR = 33999,
	FIRSTEASING = LINEAR,
	EASEINSINE,
	EASEOUTSINE,
	EASEINOUTSINE,	
	EASEINCUBIC,
	EASEOUTCUBIC,
	EASEINOUTCUBIC,
  EASEINOUTELASTIC,
	LASTEASING = EASEINOUTELASTIC,
/*	EASEINCIRC,
	EASEOUTCIRC,
	EASEINOUTCIRC,
	EASEINBACK,
	EASEOUTBACK,
	EASEINOUTBACK,
	EASEINBOUNCE,
	EASEOUTBOUNCE,
	EASEINOUTBOUNCE,
	EASEINEXPO,
	EASEOUTEXPO,
	EASEINOUTEXPO,
	EASEINELASTIC,
	EASEOUTELASTIC,
	EASEINOUTELASTIC,
	EASEINQUAD,
	EASEOUTQUAD,
	EASEINOUTQUAD,
	EASEINQUART,
	EASEOUTQUART,
	EASEINOUTQUART,
	EASEINQUINT,
	EASEOUTQUINT,
	EASEINOUTQUINT,
*/
} krad_ease_t;

#endif
