#!/usr/bin/env python

from waflib.Errors import ConfigurationError
#krad_flac_ebml_test.c

programs = """
krad_flac_test.c
""".split()

sources = """
krad_flac.c
""".split()

depsources = """
../krad_tone/krad_tone.c
../krad_audio/krad_audio.c
../krad_jack/krad_jack.c
../krad_pulse/krad_pulse.c
../krad_alsa/krad_alsa.c
../krad_ring/krad_ring.c
""".split()

includedirs = """
../krad_tone/
../krad_audio/
../krad_jack/
../krad_pulse/
../krad_alsa/
../krad_ring/
../../krad_ebml/
""".split()


def configure(conf):
	
	conf.env.libs = ["turbojpeg", "flac", "libpulse", "jack", "alsa"]
	conf.env.notlibs = []
	
	for l in conf.env.libs:
	  try:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')
	  except ConfigurationError:
		conf.env.notlibs.append(l)
		conf.env.libs.remove(l)
		
def build(bld):


	print bld.env.libs

	print bld.env.notlibs

	for p in programs:

		bld(features = 'c cprogram', 
			source = sources + depsources + [p], 
			includes = includedirs, 
			target = p.replace(".c", ""),
			use = "kradebml",
			uselib = bld.env.libs)

