#!/usr/bin/env python

programs1 = """
krad_dirac_test.c
""".split()

programs2 = """
krad_dirac_display_test.c
""".split()

sources = """
krad_dirac.c
""".split()

depsources1 = """
""".split()

depsources2 = """
../krad_display/krad_sdl_opengl_display.c
""".split()

includedirs1 = """
""".split()

includedirs2 = """
../krad_display/
""".split()

libs1 = ["orc-0.4", "schroedinger-1.0"]
libs2 = libs1 + ["sdl", "gtk+-3.0", "gl", "glu", "libswscale", "libavutil"]

def configure(conf):
	
	for l in libs1:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')

	for l in libs2:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')


def build(bld):


	for p in programs1:

		bld(features = 'c cprogram', 
			source = sources + depsources1 + [p], 
			includes = includedirs1, 
			target = p.replace(".c", ""), 
			uselib = libs1)

	for p in programs2:

		bld(features = 'c cprogram', 
			source = sources + depsources2 + [p], 
			includes = includedirs2, 
			target = p.replace(".c", ""), 
			uselib = libs2)
