




#define EBML_ID_KRAD_RADIO_CMD 0x7384
#define EBML_ID_KRAD_MIXER_CMD 0x73A4
#define EBML_ID_KRAD_COMPOSITOR_CMD 0x73C4
#define EBML_ID_KRAD_LINK_CMD 0x73C5

#define EBML_ID_KRAD_RADIO_MSG 0x437C
#define EBML_ID_KRAD_MIXER_MSG 0x450D
#define EBML_ID_KRAD_LINK_MSG 0x6911
#define EBML_ID_KRAD_COMPOSITOR_MSG 0x53B8

#define EBML_ID_KRAD_RADIO_CMD_WEB_ENABLE 0xCE
#define EBML_ID_KRAD_RADIO_CMD_WEB_DISABLE 0xCD

#define EBML_ID_KRAD_RADIO_CMD_SET_TAG 0xAE
#define EBML_ID_KRAD_RADIO_CMD_GET_TAG 0xD7
#define EBML_ID_KRAD_RADIO_CMD_LIST_TAGS 0xB9

#define EBML_ID_KRAD_RADIO_HTTP_PORT 0xCA
#define EBML_ID_KRAD_RADIO_WEBSOCKET_PORT 0xCB

#define EBML_ID_KRAD_RADIO_TAG_LIST 0x9C
#define EBML_ID_KRAD_RADIO_TAG 0x88

#define EBML_ID_KRAD_RADIO_TAG_NAME 0x45A3
#define EBML_ID_KRAD_RADIO_TAG_VALUE 0x4487


#define EBML_ID_KRAD_COMPOSITOR_CMD_HEX_DEMO 0x6624
#define EBML_ID_KRAD_COMPOSITOR_HEX_X 0x66FC
#define EBML_ID_KRAD_COMPOSITOR_HEX_Y 0x66BF
#define EBML_ID_KRAD_COMPOSITOR_HEX_SIZE 0x66A5


#define EBML_ID_KRAD_MIXER_PORTGROUP_CREATED 0xE0 // Broadcast
#define EBML_ID_KRAD_MIXER_PORTGROUP_DESTROYED 0xAA // Broadcast

#define EBML_ID_KRAD_MIXER_CMD_LIST_PORTGROUPS 0xB0
#define EBML_ID_KRAD_MIXER_CMD_CREATE_PORTGROUP 0xEA
#define EBML_ID_KRAD_MIXER_CMD_DESTROY_PORTGROUP 0xDB
#define EBML_ID_KRAD_MIXER_PORTGROUP_LIST 0xBA
#define EBML_ID_KRAD_MIXER_PORTGROUP 0xE1

#define EBML_ID_KRAD_MIXER_PORTGROUP_NAME 0xE2
#define EBML_ID_KRAD_MIXER_PORTGROUP_CHANNELS 0xE3
#define EBML_ID_KRAD_MIXER_PORTGROUP_DIRECTION 0xAF
#define EBML_ID_KRAD_MIXER_PORTGROUP_TYPE 0xE4
#define EBML_ID_KRAD_MIXER_PORTGROUP_VOLUME 0xE5
#define EBML_ID_KRAD_MIXER_PORTGROUP_MIXBUS 0xE6

#define EBML_ID_KRAD_MIXER_CMD_SET_CONTROL 0xA7
#define EBML_ID_KRAD_MIXER_CMD_GET_CONTROL 0xAB
#define EBML_ID_KRAD_MIXER_CONTROL 0xA1


#define EBML_ID_KRAD_MIXER_CONTROL_NAME 0xF7
#define EBML_ID_KRAD_MIXER_CONTROL_VALUE 0xF1


#define EBML_ID_KRAD_LINK_CMD_LIST_LINKS 0xB7
#define EBML_ID_KRAD_LINK_CMD_CREATE_LINK 0xED
#define EBML_ID_KRAD_LINK_CMD_DESTROY_LINK 0xE9
#define EBML_ID_KRAD_LINK_CMD_UPDATE_LINK 0xB3

#define EBML_ID_KRAD_LINK_LINK_NUMBER 0xB5



#define EBML_ID_KRAD_LINK_LINK_LIST 0xC0

#define EBML_ID_KRAD_LINK_LINK 0xC1
#define EBML_ID_KRAD_LINK_LINK_OPERATION_MODE 0xC2
#define EBML_ID_KRAD_LINK_LINK_TRANSPORT_MODE 0xC3
#define EBML_ID_KRAD_LINK_LINK_AV_MODE 0xC4

#define EBML_ID_KRAD_LINK_LINK_FILEPATH 0xC5

#define EBML_ID_KRAD_LINK_LINK_HOST 0xC6
#define EBML_ID_KRAD_LINK_LINK_PORT 0xC7
#define EBML_ID_KRAD_LINK_LINK_MOUNT 0xC8
#define EBML_ID_KRAD_LINK_LINK_PASSWORD 0xC9

