




#define EBML_ID_KRAD_RADIO_CMD 0x7384
#define EBML_ID_KRAD_MIXER_CMD 0x73A4
#define EBML_ID_KRAD_LINK_CMD 0x73C5

#define EBML_ID_KRAD_RADIO_MSG 0x437C
#define EBML_ID_KRAD_MIXER_MSG 0x450D
#define EBML_ID_KRAD_LINK_MSG 0x6911

#define EBML_ID_KRAD_RADIO_CMD_SET_TAG 0xAE
#define EBML_ID_KRAD_RADIO_CMD_GET_TAG 0xD7
#define EBML_ID_KRAD_RADIO_CMD_LIST_TAGS 0xB9
#define EBML_ID_KRAD_RADIO_TAG_LIST 0x9C
#define EBML_ID_KRAD_RADIO_TAG 0x88

#define EBML_ID_KRAD_RADIO_TAG_NAME 0x45A3
#define EBML_ID_KRAD_RADIO_TAG_VALUE 0x4487

#define EBML_ID_KRAD_RADIO_CMD_SET_CONTROL 0xA7
#define EBML_ID_KRAD_RADIO_CMD_GET_CONTROL 0xAB
#define EBML_ID_KRAD_RADIO_CONTROL 0xA1
