#!/usr/bin/env python

programs = """
krad_radio_daemon.c
""".split()

programs2 = """
krad_radio.c
krad_radio_ncurses.c
krad_radio_gtk.c
""".split()

sources = """
""".split()

# FIXME option builds
# FIXME ../tools/krad_wayland/krad_wayland.c
# FIXME ../tools/krad_codec2/krad_codec2.c

depsources = """
../tools/krad_link/krad_link_common.c
../tools/krad_system/krad_system.c
../tools/krad_ticker/krad_ticker.c
../tools/krad_xmms2/krad_xmms2.c
../tools/krad_ebml/krad_ebml.c
../tools/krad_compositor/krad_compositor.c
../tools/krad_framepool/krad_framepool.c
../tools/krad_osc/krad_osc.c
../tools/krad_web/ext/cJSON.c
../tools/krad_web/krad_http.c
../tools/krad_web/krad_websocket.c
../tools/krad_effects/digilogue.c
../tools/krad_effects/fastlimiter.c
../tools/krad_effects/util/blo.c
../tools/krad_effects/util/db.c
../tools/krad_effects/util/buffer.c
../tools/krad_effects/util/iir.c
../tools/krad_effects/util/rms.c
../tools/krad_effects/pass.c
../tools/krad_effects/djeq.c
../tools/krad_effects/hardlimiter.c
../tools/krad_effects/sidechain_comp.c
../tools/krad_ipc/krad_ipc_client.c
../tools/krad_ipc/krad_ipc_server.c
../tools/krad_tags/krad_tags.c
../tools/krad_radio/krad_radio.c
../tools/krad_mixer/krad_mixer.c
../tools/krad_tone/krad_tone.c
../tools/krad_audio/krad_audio.c
../tools/krad_jack/krad_jack.c
../tools/krad_pulse/krad_pulse.c
../tools/krad_alsa/krad_alsa.c
../tools/krad_alsa/krad_alsa_seq.c
../tools/krad_vpx/krad_vpx.c
../tools/krad_dirac/krad_dirac.c
../tools/krad_theora/krad_theora.c
../tools/krad_vorbis/krad_vorbis.c
../tools/krad_flac/krad_flac.c
../tools/krad_opus/krad_opus.c
../tools/krad_opus/opus_header.c
../tools/krad_gui/krad_gui.c
../tools/krad_v4l2/krad_v4l2.c
../tools/krad_gui/krad_gui_gtk.c
../tools/krad_ring/krad_ring.c
../tools/krad_link/krad_link.c
../tools/krad_transmitter/krad_transmitter.c
../tools/krad_io/krad_io.c
../tools/krad_ogg/krad_ogg.c
../tools/krad_container/krad_container.c
../tools/krad_x11/krad_x11.c
../tools/krad_udp/krad_udp.c
../tools/krad_decklink/krad_decklink.c
../tools/krad_decklink/krad_decklink_capture.cpp
../tools/krad_decklink/vendor/DeckLinkAPIDispatch.cpp
""".split()

depsources2 = """
../tools/krad_system/krad_system.c
../tools/krad_ebml/krad_ebml.c
../tools/krad_link/krad_link_common.c
../tools/krad_ipc/krad_ipc_client.c
../tools/krad_osc/krad_osc.c
../tools/krad_alsa/krad_alsa_seq.c
""".split()

includedirs = """
../tools/krad_compositor/
../tools/krad_ticker/
../tools/krad_xmms2/
../tools/krad_framepool/
../tools/krad_web/
../tools/krad_web/ext/
../tools/krad_web/res/
../tools/krad_effects/
../tools/krad_tone/
../tools/krad_ipc/
../tools/krad_tags/
../tools/krad_audio/
../tools/krad_wayland/
../tools/krad_dirac/
../tools/krad_theora/
../tools/krad_jack/
../tools/krad_pulse/
../tools/krad_alsa/
../tools/krad_mixer/
../tools/krad_osc/
../tools/krad_xmms2/
../tools/krad_wayland/
../tools/krad_vpx/
../tools/krad_v4l2/
../tools/krad_flac/
../tools/krad_vorbis/
../tools/krad_gui/
../tools/krad_opus/
../tools/krad_radio/
../tools/krad_ring/
../tools/krad_ogg/
../tools/krad_io/
../tools/krad_link/
../tools/krad_transmitter/
../tools/krad_container/
../tools/krad_x11/
../tools/krad_udp/
../tools/krad_codec2/
../tools/krad_system/
../tools/krad_decklink/
../tools/krad_decklink/vendor
../tools/krad_ebml/
/usr/local/include
/usr/include
""".split()

libs = ["samplerate", "turbojpeg", "theora", "theoraenc", "theoradec", "vorbis", "vorbisenc", "opus", 
		"x11-xcb", "xcb-atom", "xcb-image", "xcb", "x11", "orc-0.4", "schroedinger-1.0", "gtk+-3.0", "gl", "glu", 
		"flac", "libpulse", "jack", "alsa", "vpx", "libswscale", "libavutil", "websockets", "ncurses", "xmms2-client"]

# FIXME option builds
# libs = libs + ["wayland-client", "codec2"] 

def configure(conf):
	
	for l in libs:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')


def build(bld):

	cmd = 'xxd -i tools/krad_web/res/krad_radio.html tools/krad_web/res/krad_radio.html.h'
	bld.exec_command(cmd)

	cmd = 'xxd -i tools/krad_web/res/krad_radio.js tools/krad_web/res/krad_radio.js.h'
	bld.exec_command(cmd)

	for p in programs:

		bld(features = 'c cprogram cxx cxxprogram', 
			source = sources + depsources + [p], 
			includes = includedirs, 
			target = p.replace(".c", ""),
			use = ["m"],
			uselib = libs)

	for p in programs2:

		bld(features = 'c cprogram', 
			source = sources + depsources2 + [p], 
			includes = includedirs, 
			target = p.replace(".c", ""),
			use = ["m"],
			uselib = libs)

