#!/usr/bin/env python

import os

programs = """
krad_radio_daemon.c
""".split()

programs2 = """
krad_radio.c
krad_radio_ap.c
krad_radio_vp.c
""".split()

#krad_radio_ncurses.c
#krad_radio_gtk.c

sources = """
""".split()

depsources = """
../tools/krad_link/krad_link_common.c
../tools/krad_system/krad_system.c
../tools/krad_ticker/krad_timer.c
../tools/krad_ticker/krad_ticker.c
../tools/krad_xmms2/krad_xmms2.c
../tools/krad_ee/krad_x264.c
../tools/krad_ebml/krad_ebml.c
../tools/krad_compositor/krad_sprite.c
../tools/krad_compositor/krad_text.c
../tools/krad_compositor/krad_easing.c
../tools/krad_compositor/krad_compositor.c
../tools/krad_framepool/krad_framepool.c
../tools/krad_osc/krad_osc.c
../tools/krad_web/ext/cJSON.c
../tools/krad_web/krad_http.c
../tools/krad_web/krad_websocket.c
../tools/krad_sfx/krad_eq.c
../tools/krad_sfx/krad_pass.c
../tools/krad_sfx/krad_rushlimiter.c
../tools/krad_sfx/krad_sfx.c
../tools/krad_ipc/krad_ipc_client.c
../tools/krad_ipc/krad_ipc_server.c
../tools/krad_tags/krad_tags.c
../tools/krad_radio/krad_radio.c
../tools/krad_mixer/krad_mixer.c
../tools/krad_tone/krad_tone.c
../tools/krad_audio/krad_audio.c
../tools/krad_jack/krad_jack.c
../tools/krad_ring/krad_resample_ring.c
../tools/krad_vpx/krad_vpx.c
../tools/krad_theora/krad_theora.c
../tools/krad_vorbis/krad_vorbis.c
../tools/krad_flac/krad_flac.c
../tools/krad_opus/krad_opus.c
../tools/krad_opus/opus_header.c
../tools/krad_gui/krad_gui.c
../tools/krad_ring/krad_ring.c
../tools/krad_link/krad_link.c
../tools/krad_transmitter/krad_transmitter.c
../tools/krad_io/krad_io.c
../tools/krad_ogg/krad_ogg.c
../tools/krad_container/krad_container.c
../tools/krad_x11/krad_x11.c
../tools/krad_udp/krad_udp.c
../tools/krad_decklink/krad_decklink.c
../tools/krad_decklink/krad_decklink_capture.cpp
""".split()

depsources2 = """
../tools/krad_system/krad_system.c
../tools/krad_ebml/krad_ebml.c
../tools/krad_ring/krad_ring.c
../tools/krad_transmitter/krad_transmitter.c
../tools/krad_link/krad_link_common.c
../tools/krad_ipc/krad_ipc_client.c
../tools/krad_osc/krad_osc.c
../tools/krad_tone/krad_tone.c
""".split()

includedirs = """
../tools/krad_ee/
../tools/krad_compositor/
../tools/krad_ticker/
../tools/krad_xmms2/
../tools/krad_framepool/
../tools/krad_web/
../tools/krad_web/ext/
../tools/krad_web/res/
../tools/krad_sfx/
../tools/krad_tone/
../tools/krad_ipc/
../tools/krad_tags/
../tools/krad_audio/
../tools/krad_theora/
../tools/krad_jack/
../tools/krad_alsa/
../tools/krad_mixer/
../tools/krad_osc/
../tools/krad_xmms2/
../tools/krad_wayland/
../tools/krad_vpx/
../tools/krad_v4l2/
../tools/krad_flac/
../tools/krad_vorbis/
../tools/krad_gui/
../tools/krad_opus/
../tools/krad_radio/
../tools/krad_ring/
../tools/krad_ogg/
../tools/krad_io/
../tools/krad_link/
../tools/krad_transmitter/
../tools/krad_container/
../tools/krad_x11/
../tools/krad_udp/
../tools/krad_codec2/
../tools/krad_system/
../tools/krad_decklink/
../tools/krad_ebml/
../tools/krad_legacy/
/usr/local/include
/usr/include
""".split()

libs = ["samplerate", "x264", "turbojpeg", "theora", "theoraenc", "theoradec", "vorbis", "vorbisenc", "opus", 
		"cairo", "x11-xcb", "xcb-image", "xcb", "x11",
		"flac", "jack", "vpx", "libswscale", "libavutil", "libwebsockets", "xmms2-client"]

# "ncurses",

def check_system(systm):

	global includedirs
	global depsources
	global depsources2
	global libs
	global programs2

	if systm.env['IS_LINUX']:
		libs = libs + ["alsa"]    
		depsources = ["../tools/krad_v4l2/krad_v4l2.c", "../tools/krad_alsa/krad_alsa.c",
		"../tools/krad_alsa/krad_alsa_seq.c"] + depsources
		depsources2 = ["../tools/krad_alsa/krad_alsa.c", "../tools/krad_alsa/krad_alsa_seq.c"] + depsources2
		programs2 = ["krad_radio_ev.c"] + programs2
		includedirs = ["../tools/krad_decklink/vendor/linux"] + includedirs
		depsources = ["../tools/krad_decklink/vendor/linux/DeckLinkAPIDispatch.cpp"] + depsources


	if systm.env['IS_MACOSX']:
		depsources = ["../tools/krad_legacy/krad_mach.c"] + depsources
		depsources2 = ["../tools/krad_legacy/krad_mach.c"] + depsources2
		includedirs = ["/opt/libjpeg-turbo/include"] + includedirs
		includedirs = ["../tools/krad_decklink/vendor/osx"] + includedirs
		depsources = ["../tools/krad_decklink/vendor/osx/DeckLinkAPIDispatch.cpp"] + depsources

def check_way(way):

	global depsources
	global libs

	if way.env['WAYRAD']:
		depsources += ["../tools/krad_wayland/krad_wayland.c"]
		libs += ["wayland-client"]

def remake_webres(web):
	cmd = 'xxd -i tools/krad_web/res/krad_radio.html tools/krad_web/res/krad_radio.html.h'
	web.exec_command(cmd)

	cmd = 'xxd -i tools/krad_web/res/krad_radio.js tools/krad_web/res/krad_radio.js.h'
	web.exec_command(cmd)


def configure(conf):

	remake_webres(conf)	
	check_way(conf)
	check_system(conf)

	for l in libs:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')


def build(bld):

	remake_webres(bld)
	check_way(bld)
	check_system(bld)

	for p in programs:

		bld(features = 'c cprogram cxx cxxprogram', 
			source = sources + depsources + [p], 
			includes = includedirs, 
			target = p.replace(".c", ""),
			uselib = libs)

	for p in programs2:

		bld(features = 'c cprogram', 
			source = sources + depsources2 + [p], 
			includes = includedirs, 
			target = p.replace(".c", ""),
			uselib = libs)

