#!/usr/bin/env python

programs = """
krad_list_test.c
""".split()

sources = """
krad_list.c
""".split()

depsources = """
""".split()

includedirs = """
""".split()

libs = ["libxml-2.0"]

def configure(conf):
	
	for l in libs:
		conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')


def build(bld):


	for p in programs:

		bld(features = 'c cprogram', 
			source = sources + depsources + [p], 
			includes = includedirs, 
			target = p.replace(".c", ""), 
			uselib = libs)

