#!/usr/bin/env python

programs = """
krad_ebml_fileinfo.c
""".split()

sources = """
""".split()

depsources = """
""".split()

includedirs = """
../../krad_ebml/
""".split()

libs = ["turbojpeg"]

def configure(conf):
	pass
	#for l in libs:
	#	conf.check_cfg(package = l, uselib_store = l, args='--cflags --libs')


def build(bld):


	for p in programs:

		bld(features = 'c cprogram', 
			source = sources + depsources + [p], 
			includes = includedirs, 
			target = p.replace(".c", ""),
			use = "kradebml",
			uselib = libs)
