#!/usr/bin/env python

KRADEBML_VERSION = '3.01'

sources = """
krad_ebml.c
kradebml.pc.in
""".split()

depsources = """
""".split()

includedirs = """
""".split()


sources2 = """
krad_ebml.c
kradebml.pc.in
""".split()

depsources2 = """
""".split()

includedirs2 = """
""".split()

def configure(conf):

	conf.env['KRADEBML_VERSION'] = KRADEBML_VERSION
	conf.define('KRADEBML_VERSION', KRADEBML_VERSION)
	
def build(bld):

	bld.shlib(
		source = sources + depsources, 
		includes = includedirs, 
		target = "kradebml",
		lib = ["m"],
		vnum = KRADEBML_VERSION)
		
	bld.add_post_fun(post)

def post(ctx):
	if ctx.cmd == 'install' and ctx.env['IS_LINUX'] == True: 
		ctx.exec_command('/sbin/ldconfig')
